name: ecommerce_store
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  #language 
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Core
  connectivity_plus: ^5.0.2
  flutter_dotenv: ^5.1.0
  flutter_screenutil: ^5.9.0
  flutter_native_splash: ^2.3.10
  get_it: ^8.2.0

  #UI
  animate_do: ^4.2.0
  fluttertoast: ^8.2.4
  flutter_zoom_drawer: ^3.1.2
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  flutter_animate: ^4.5.0
  webview_flutter: ^4.7.0
  package_info_plus: ^8.3.1
  carousel_slider: ^5.1.1
  share_plus: ^11.1.0
  badges: ^3.1.2

  #Bloc
  flutter_bloc: ^9.1.1
  #shared preferences
  shared_preferences: ^2.2.2
  #freezed
  freezed_annotation: ^2.4.1

  #Firebase
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12

  #image picker
  image_picker: ^1.0.7
  permission_handler: ^12.0.1

  #APi
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.3

  #Notifications
  # firebase_messaging: ^15.2.10
  # intl: ^0.20.2

  #local database Hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #Patination
  equatable: ^2.0.5
  bloc_concurrency: ^0.3.0
  # firebase_dynamic_links: ^6.1.10
  # flutter_local_notifications: ^19.4.0
  
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  very_good_analysis: ^9.0.0
  analyzer: ^6.11.0

  # dart run build_runner build --delete-conflicting-outputs
  build_runner: ^2.4.8
  freezed: ^2.5.2
  retrofit_generator: ^9.2.0
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/app_icon.jpg"


flutter:

  uses-material-design: true


  assets:
    - .env.dev
    - .env.prod
    - lang/ar.json
    - lang/en.json
    - assets/images/core/
    - assets/images/admin/
    - assets/images/customer/
    - assets/svg/


  fonts:
    # Arabic Font
    - family: Cairo
      fonts:
        - asset: assets/fonts/arabic/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/arabic/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/arabic/cairo/Cairo-Regular.ttf
          weight: 400
    # English Font
    - family: Poppins
      fonts:
        - asset: assets/fonts/english/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/english/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/english/poppins/Poppins-Regular.ttf
          weight: 400
